[livesmarter]
title = "오디오클립 ─ 듣똑라"
url = "https://audioclip.naver.com/channels/310"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[jtbc_news]
title = "오디오클립 ─ JTBC 뉴스룸"
url = "https://audioclip.naver.com/channels/2946"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[sbs_news]
title = "오디오클립 ─ 귀로 듣는 스브스"
url = "https://audioclip.naver.com/channels/3245"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[sbs_golroom]
title = "오디오클립 ─ SBS 골라듣는 뉴스룸"
url = "https://audioclip.naver.com/channels/508"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[sbs_coverage]
title = "오디오클립 ─ SBS 취재파일"
url = "https://audioclip.naver.com/channels/3244"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[sbs_newstory]
title = "오디오클립 ─ SBS 뉴스토리"
url = "https://audioclip.naver.com/channels/2914"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[sbs_unanswered]
title = "오디오클립 ─ SBS 그것이 알고싶다"
url = "https://audioclip.naver.com/channels/2968"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[kbs_news]
title = "오디오클립 ─ KBS 뉴스"
url = "https://audioclip.naver.com/channels/1847"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[channela_newsa]
title = "오디오클립 ─ 채널A 뉴스A"
url = "https://audioclip.naver.com/channels/3117"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[channela_newstop10]
title = "오디오클립 ─ 채널A 뉴스 TOP 10"
url = "https://audioclip.naver.com/channels/3118"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[tvchosun_news9]
title = "오디오클립 ─ TV조선 뉴스9"
url = "https://audioclip.naver.com/channels/3108"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[mbn_news]
title = "오디오클립 ─ MBN 종합뉴스"
url = "https://audioclip.naver.com/channels/2994"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[ytn_news]
title = "오디오클립 ─ YTN 최신 뉴스"
url = "https://audioclip.naver.com/channels/197"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[yonhapnewstv_newswatch]
title = "오디오클립 ─ 연합뉴스TV 뉴스워치"
url = "https://audioclip.naver.com/channels/3089"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[hankyung_newslabit]
title = "오디오클립 ─ 한국경제 뉴스래빗"
url = "https://audioclip.naver.com/channels/1137"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[cbs_news]
title = "오디오클립 ─ CBS뉴스"
url = "https://audioclip.naver.com/channels/1635"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[cbs_newsshow]
title = "오디오클립 ─ CBS 김현정의 뉴스쇼"
url = "https://audioclip.naver.com/channels/1256"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[americaknow]
title = "오디오클립 ─ 아메리카노"
url = "https://audioclip.naver.com/channels/3934"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[bookjournalism]
title = "오디오클립 ─ 북저널리즘 라디오"
url = "https://audioclip.naver.com/channels/2939"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[3protv]
title = "오디오클립 ─ 삼프로TV 경제의 신과함께"
url = "https://audioclip.naver.com/channels/6519"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"