[audioclip_livesmarter]
title = "오디오클립 ─ 듣똑라"
url = "https://audioclip.naver.com/channels/310"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[audioclip_sbsnews]
title = "오디오클립 ─ 귀로 듣는 스브스"
url = "https://audioclip.naver.com/channels/3245"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"

[audioclip_sbsgolroom]
title = "오디오클립 ─ SBS 골라듣는 뉴스룸"
url = "https://audioclip.naver.com/channels/508"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"